config/routes.rb
Snorby::Application.routes.draw do

  resources :lookups

  # This feature is not ready yet
  # resources :notifications

  resources :jobs do
    member do
      get :last_error
      get :handler
    end
  end

  resources :classifications

  devise_for :users, :path_names => { :sign_in => 'login', 
    :sign_out => 'logout', 
    :sign_up => 'register' }, :controllers => { 
      :registrations => "registrations",
      :sessions => "sessions", 
      :passwords => 'passwords'
    } do
    get "/login" => "devise/sessions#new"
    get '/logout', :to => "devise/sessions#destroy"
    get '/reset/password', :to => "devise/passwords#edit"
  end

  root :to => "page#dashboard"

  resources :sensors do


    collection do
      get :agent_list
    end
  end

  resources :settings do
    collection do
      get :restart_worker
      get :start_sensor_cache
      get :start_daily_cache
      get :start_geoip_update
      get :start_worker
    end
  end

  resources :signatures do

    collection do
      get :search
    end
    
  end

  resources :severities do
  end


  match '/dashboard', :controller => 'Page', :action => 'dashboard'
  match '/search', :controller => 'Page', :action => 'search'
  match '/results', :controller => 'Page', :action => 'results'
  match '/force/cache', :controller => "Page", :action => 'force_cache'
  match '/cache/status', :controller => "Page", :action => 'cache_status'
  match '/search/json', :controller => "Page", :action => 'search_json'

  resources :saved_searches, :path => "/saved/searches" do
    
    collection do
      post :title
      post :update
    end

    member do
      get :view
      post :update
    end
  end

  match ':controller(/:action(/:sid/:cid))', :controller => 'Events'

  resources :asset_names do
    member do
      delete :remove
    end

    collection do
      post :add
      get :lookup
      post :bulk_upload
      get 'get_bulk_upload', action: :get_bulk_upload, as: 'get_bulk_upload'
    end
  end

  resources :events do
    
    resources :notes do
      
    end
    
    collection do
      get :sessions
      get :view
      get :create_mass_action
      post :mass_action
      get :create_email
      post :email
      get :hotkey
      post :export
      get :lookup
      get :rule
      get :packet_capture
      get :history
      post :classify
      post :classify_sessions
      post :mass_update
      get :queue
      post :favorite
      get :last
      get :since
      get :activity
    end
    
  end
  
  resources :notes

  resources :users do
    collection do
      post :toggle_settings
      post :remove
      post :add
    end
  end

  resources :page do
    collection do
      get :search
      get :results
    end
  end

end

app/models/setting.rb
class Setting

  CHECKBOXES = [
    :utc,
    :event_notifications,
    :update_notifications,
    :daily,
    :weekly,
    :monthly,
    :lookups,
    :notes,
    :packet_capture,
    :packet_capture_auto_auth,
    :autodrop,
    :geoip
  ]

  include DataMapper::Resource

  property :name, String, :key => true, :index => true, :required => false

  property :value, Object

  def checkbox?
    return true if CHECKBOXES.include?(name.to_sym)
    false
  end

  def self.set(name, value=nil)
    record = first(:name => name)
    return Setting.create(:name => name, :value => value) if record.nil?
    record.update(:value => value)
  end

  def self.find(name)
    record = first(:name => name)
    return false if record.nil?
    return false if record.value.is_a?(Integer) && record.value.zero?
    record.value
  end

  def self.has_setting(name)
    record = first(:name => name)
    return false if record.nil?
    return false if record.value.is_a?(Integer) && record.value.zero?
    return true unless record.value.blank?
    false
  end

  def self.file(name, file)
    new_file_name = file.original_filename.sub(/(\w+)(?=\.)/, "#{name}")
    new_file_path = "#{Rails.root.to_s}/public/system/#{new_file_name}"

    FileUtils.mv(file.tempfile.path, new_file_path)
    self.set(:logo, "#{Snorby::CONFIG[:baseuri]}/system/#{new_file_name}")
  end

  def self.method_missing(method, *args)
    if method.to_s.match(/^all/)
      super
    elsif method.to_s.match(/^(.*)=$/)
      return Setting.set($1, args.first)
    elsif method.to_s.match(/^(.*)\?$/)
      Setting.has_setting($1.to_sym)
    else
      return Setting.get(method.to_sym)
    end
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  before_filter :require_administrative_privileges

  def index
  end

  def create
    @params = params[:settings]
    @settings = Setting.all

    @settings.each do |setting|
      name = setting.name
      
      if @params.keys.include?(name)
        if @params[name].kind_of?(ActionDispatch::Http::UploadedFile)
          Setting.file(name, @params[name])
        else
          setting.update(:value => @params[name])
        end
      else
        setting.update(:value => nil) if setting.checkbox?
      end
    end

    redirect_to settings_path, :notice => 'Settings Updated Successfully.'
  end

  def update

  end

  def start_worker
    Snorby::Worker.start unless Snorby::Worker.running?
    redirect_to jobs_path
  end

  def start_sensor_cache
    Snorby::Jobs.sensor_cache.destroy! if Snorby::Jobs.sensor_cache?
    Delayed::Job.enqueue(Snorby::Jobs::SensorCacheJob.new(false), :priority => 1)
    redirect_to jobs_path
  end

  def start_daily_cache
    Snorby::Jobs.daily_cache.destroy! if Snorby::Jobs.daily_cache?
    Delayed::Job.enqueue(Snorby::Jobs::DailyCacheJob.new(false), :priority => 1, :run_at => Time.now.tomorrow.beginning_of_day)
    redirect_to jobs_path
  end
  
  def start_geoip_update
    Snorby::Jobs.geoip_update.destroy! if Snorby::Jobs.geoip_update?
    Delayed::Job.enqueue(Snorby::Jobs::GeoipUpdatedbJob.new(false), :priority => 1, :run_at => 1.week.from_now.beginning_of_day)
    redirect_to jobs_path
  end

  def restart_worker
    Snorby::Worker.restart if Snorby::Worker.running?
    redirect_to jobs_path
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_menu.html.erb
<% if Snorby::Worker.problems? %>

	<%= drop_down_for('Worker Options', 'icons/worker.png', 'worker') do %>
	
		<% if Snorby::Worker.running? %>
			<%= drop_down_item "Start Sensor Cache Job", start_sensor_cache_settings_path unless Snorby::Jobs.sensor_cache? %>
			<%= drop_down_item "Start GeoIP Database Update Job", start_geoip_update_settings_path if (Setting.geoip? && !Snorby::Jobs.geoip_update?) %>			
		<% else %>
			<%= drop_down_item "Start Worker", start_worker_settings_path %>
		<% end %>
		
	<% end %>

<% end %>

app/views/settings/index.html.erb
<%= title "General Settings" do -%>

	<%= render :partial => 'settings/menu' %>
	
<%- end -%>

<div id='general-settings', class='grid_12 page boxit'>
	
	<%= form_tag Snorby::CONFIG[:baseuri] + '/settings', :multipart => true, :class => 'basic-form validate' do %>
	
	
	<div id='form-holder'>
		
		<div class='grid_6'>
			<p>
				<%= label_tag 'Company Name' %><br />
				<%= text_field_tag '[settings][company]', (Setting.company ? Setting.find(:company) : nil), :placeholder => 'Company Name', :autocomplete => :off, :class => 'required' %>
			</p>

			<p>
				<%= label_tag 'Company Email' %> <i>(this email will be used as the report sender)</i><br />
				<%= text_field_tag '[settings][email]', (Setting.email ? Setting.find(:email) : nil), :placeholder => 'Company Email', :autocomplete => :off, :class => 'required email' %>
			</p>
			
			<p>
				<%= label_tag 'Signature Lookup URL' %> <i>(user $$sid$$ and $$gid$$ for the get request parameters)</i><br />
				<%= text_field_tag '[settings][signature_lookup]', (Setting.signature_lookup ? Setting.find(:signature_lookup) : nil), :placeholder => 'Signature Lookup URL', :autocomplete => :off, :class => 'required url' %>
			</p>

			<p>
				<%= check_box_tag '[settings][update_notifications]', 0, (Setting.update_notifications ? Setting.find(:update_notifications) : nil) %> <%= label_tag 'Enable Snorby Update Notifications' %><br />
        <i>(DEPRECATED Notification reminder when a new Snorby build is released)</i>
			</p>

			<p class='_settings_packet_capture'>
				<%= check_box_tag '[settings][packet_capture]', 0, (Setting.packet_capture ? Setting.find(:packet_capture) : nil) %> <%= label_tag 'Enable Packet Capture Support' %><br />
				<i>(Enable the Snorby Packet Capture Plugin)</i>
      </p>

		</div>

		<div class='grid_5'>
            <% if not Snorby::CONFIG[:user_reports_control] %>
			<p>
				<%= check_box_tag '[settings][daily]', 1, (Setting.daily ? Setting.find(:daily) : nil) %> <%= label_tag 'Daily Reports' %><br />
				<i>(Send a report summarizing the captured traffic daily.)</i><br />
			</p>

			<p>
				<%= check_box_tag '[settings][weekly]', 1, (Setting.weekly ? Setting.find(:weekly) : nil) %> <%= label_tag 'Weekly Reports' %><br />
				<i>(Send a report summarizing the captured traffic weekly)</i><br />
			</p>

			<p>
				<%= check_box_tag '[settings][monthly]', 1, (Setting.monthly ? Setting.find(:monthly) : nil) %> <%= label_tag 'Monthly Reports' %><br />
				<i>(Send a report summarizing the captured traffic monthly)</i><br />
			</p>
        <% end %>

			<p>
				<%= check_box_tag '[settings][lookups]', 1, (Setting.lookups ? Setting.find(:lookups) : nil) %> <%= label_tag 'Address Lookups' %><br />
				<i>(This option enables the analyst to perform basic queries on source & destination addresses using external sources.)</i><br />
			</p>

			<p>
				<%= check_box_tag '[settings][event_notifications]', 0, (Setting.event_notifications ? Setting.find(:event_notifications) : false) %> <%= label_tag 'Enable Global Event Notifications' %><br />
        <i>(Show new event notifications globally. Event count since last check time.)</i>
			</p>

			<p>
				<%= check_box_tag '[settings][geoip]', 1, Setting.find(:geoip) %> <%= label_tag 'GeoIP' %><br />
				<i>(Display GeoIP information on the events list)</i><br />
			</p>			

			<p>
      <%= check_box_tag '[settings][autodrop]', 1, Setting.find(:autodrop) %> <%= label_tag 'Prune database when event count is greater than' %>
        <%= select_tag '[settings][autodrop_count]', "<option value='500000'>500,000</option><option value='1000000'>1,000,000</option><option value='2000000'>2,000,000</option><option value='3000000'>3,000,000</option><option value='4000000'>4,000,000</option><option value='5000000'>5,000,000</option>".html_safe, 
				{ :class => 'require', :autodrop_count => Setting.find(:autodrop_count) } %>
        <br />
        <i>(Prune the database automatically when the event count exceeds your specified limit.)</i><br />
				<br/>
			</p>

		</div>
		
	</div>	
	
	<div class='pc-settings'>
		
		<div class='grid_6'>

			<p class='pc-settings'>
				<%= label_tag 'Packet Capture Plugin:' %>
				<%= select_tag '[settings][packet_capture_type]', "<option value='openfpc'>OpenFPC</option><option value='solera'>Solera Networks</option>".html_safe, 
				{ :class => 'require', :packet_capture_plugin => Setting.find(:packet_capture_type) } %><br />
			</p>

			<p class='pc-settings'>
				<%= check_box_tag '[settings][packet_capture_auto_auth]', 1, (Setting.packet_capture_auto_auth ? Setting.find(:packet_capture_auto_auth) : nil) %> 
				<%= label_tag 'Packet Capture Auto-Authenticate' %><br />
				<i>(Pass the credentials in the get request)</i><br />
			</p>

			<p class='pc-settings'>
				<%= label_tag 'Packet Capture Extract URL' %> <i>(Packet Capture extract URL)</i><br />
				<%= text_field_tag '[settings][packet_capture_url]', (Setting.packet_capture_url ? Setting.find(:packet_capture_url) : nil), 
				:placeholder => 'Packet Capture Extract URL', :autocomplete => :off, :class => 'url' %>
			</p>

		</div>

		<div class='grid_5'>

			<p class='pc-settings'>
				<%= label_tag 'API User' %> <i>(User name for Packet Capture API)</i><br />
				<%= text_field_tag '[settings][packet_capture_user]', (Setting.packet_capture_user ? Setting.find(:packet_capture_user) : nil), 
				:placeholder => 'Packet Capture User', :autocomplete => :off, :class => '' %>
			</p>

			<p class='pc-settings'>
				<%= label_tag 'API Password' %> <i>(Password for Packet Capture API)</i><br />
				<%= password_field_tag '[settings][packet_capture_password]', (Setting.packet_capture_password ? Setting.find(:packet_capture_password) : nil), 
				:placeholder => 'Packet Capture Password', :autocomplete => :off, :class => '' %>
			</p>

		</div>
		
  </div>
	
	<%= form_actions do %>

		<%= button "Save Settings", :class => 'success' %>

		<%= button "Cancel", :class => 'warning cancel' %>

	<% end %>
		
	
	<% end %>
	
</div>

app/views/settings/severities.html.erb
<%= title "Severities Settings", do -%>

	<%= render :partial => 'settings/menu' %>
	
<%- end -%>

<div id='severities' class='boxit'>
	
	<%= title "Listing Sensors", do -%>

		<li>Hello</li>

	<%- end -%>

	<div id="sensors">

		<table border="0" cellspacing="0" cellpadding="0">
			<tr>		
				<th>ID</th>
				<th>Name</th>
				<th>Hostname</th>
				<th>Interface</th>
				<th>Event Count</th>
			</tr>
			<tbody class='sensors'>
				
				<% @severities.each do |severity| %>
					
					
					
				<% end %>
				
			</tbody>
		</table>


		<%= pager(@sensors) %>

	</div>
	
</div>